default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: loguma_succulents_development

test:
  <<: *default
  database: loguma_succulents_test

production:
  <<: *default
  database: loguma_succulents
  username: arcloguma_succulents
  url: <%= ENV['DATABASE_URL'] %>